#!/bin/bash
# gendata


# Sanity check command line options
usage() {
  printf "Usage: $0 [size]\n"
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

# will put the data to hdfs directory
# /tmp/tpch<size>g/
# first clear this directory on hdfs
# and drop the db on hive
hdfs_path="/tmp/tpch$1g/"
hdfs dfs -rm -r -f $hdfs_path
touch drop_db.hql
echo "drop database if exists tpch$1g cascade" > drop_db.hql
hive -f drop_db.hql

# build a directory to hold data
if [ ! -d "./data/" ]; then
    mkdir data/
fi
db_path="tpch$1g"
rm -rf data/$db_path
mkdir data/$db_path
echo $db_path

# go to tpch dbgen directory, remove previous tbl files and gen
cd 2.18.0_rc2/dbgen/
rm *.tbl
gen_data="./dbgen -s $1"
eval $gen_data

cd ../../
# pwd
mv 2.18.0_rc2/dbgen/*.tbl data/$db_path/

# make directories and put data to hdfs
hdfs dfs -mkdir $hdfs_path
hdfs dfs -mkdir /tmp/tpch$1g/customer/
hdfs dfs -mkdir /tmp/tpch$1g/lineitem/
hdfs dfs -mkdir /tmp/tpch$1g/nation/
hdfs dfs -mkdir /tmp/tpch$1g/orders/
hdfs dfs -mkdir /tmp/tpch$1g/part/
hdfs dfs -mkdir /tmp/tpch$1g/partsupp/
hdfs dfs -mkdir /tmp/tpch$1g/region/
hdfs dfs -mkdir /tmp/tpch$1g/supplier/

hdfs dfs -put data/$db_path/customer.tbl /tmp/tpch$1g/customer/
hdfs dfs -put data/$db_path/lineitem.tbl /tmp/tpch$1g/lineitem/
hdfs dfs -put data/$db_path/nation.tbl /tmp/tpch$1g/nation/
hdfs dfs -put data/$db_path/orders.tbl /tmp/tpch$1g/orders/
hdfs dfs -put data/$db_path/part.tbl /tmp/tpch$1g/part/
hdfs dfs -put data/$db_path/partsupp.tbl /tmp/tpch$1g/partsupp/
hdfs dfs -put data/$db_path/region.tbl /tmp/tpch$1g/region/
hdfs dfs -put data/$db_path/supplier.tbl /tmp/tpch$1g/supplier/

# create database and tables on hive
touch create_db.hql
echo "CREATE DATABASE tpch$1g;" > create_db.hql
hive -f create_db.hql
# create tables;

touch create_region.hql
echo "USE tpch$1g; CREATE TABLE region (r_regionkey INT, r_name CHAR(25), r_comment VARCHAR(152), r_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch1g/lineitem/';" > create_region.hql
hive -f create_region.hql
